#!/usr/bin/env python3
"""
Generate docker-compose-workers.yaml for running N parallel isolated benchmark workers.
Each worker runs in its own network namespace with dedicated ports and its own /trace mount.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPOSE_FILE = ROOT / "docker-compose-workers.yaml"
NUM_WORKERS = 16

lines = [
    "# ============================================================================",
    "# NetSail - 16 Isolated Parallel Benchmark Workers",
    "# Auto-generated by scripts/generate_workers_compose.py",
    "# ============================================================================",
    "",
    "services:",
]

for i in range(1, NUM_WORKERS + 1):
    dash_port = 8100 + i
    webrtc_port = 3100 + i
    rtc_min = 11000 + (i - 1) * 50
    rtc_max = rtc_min + 49

    lines.extend([
        f"  # --- Worker {i} ---",
        f"  hls-dash-worker-{i}:",
        f"    image: netsail/hls-dash-server:latest",
        f"    container_name: netsail-hls-dash-{i}",
        f"    volumes:",
        f"      - ./content:/app/content:ro",
        f"      - ./shaper/trace/worker_{i}:/trace:ro",
        f"      - ./shaper/tc-trace.py:/app/tc-trace.py:ro",
        f"    environment:",
        f'      PORT: "8080"',
        f'      HOST: "0.0.0.0"',
        f'      CONTENT_DIR: "/app/content"',
        f"    ports:",
        f'      - "{dash_port}:8080"',
        f"    cap_add:",
        f"      - NET_ADMIN",
        f"    command: >",
        f'      sh -c "python3 /app/tc-trace.py &',
        f'             python3 server.py"',
        f"    restart: unless-stopped",
        "",
        f"  webrtc-worker-{i}:",
        f"    image: netsail/webrtc-server:latest",
        f"    container_name: netsail-webrtc-{i}",
        f"    volumes:",
        f"      - ./content:/app/content:ro",
        f"      - ./shaper/trace/worker_{i}:/trace:ro",
        f"      - ./shaper/tc-trace.py:/app/tc-trace.py:ro",
        f"      - ./webrtc-server/server.js:/app/server.js:ro",
        f"    environment:",
        f'      PORT: "3000"',
        f'      HOST: "0.0.0.0"',
        f'      CONTENT_DIR: "/app/content"',
        f'      ANNOUNCED_IP: "127.0.0.1"',
        f'      INTERVAL: "0.5"',
        f'      RTC_MIN_PORT: "{rtc_min}"',
        f'      RTC_MAX_PORT: "{rtc_max}"',
        f"    ports:",
        f'      - "{webrtc_port}:3000"',
        f'      - "{rtc_min}-{rtc_max}:{rtc_min}-{rtc_max}/udp"',
        f"    cap_add:",
        f"      - NET_ADMIN",
        f"    command: >",
        f'      sh -c "node server.js"',
        f"    restart: unless-stopped",
        "",
    ])

COMPOSE_FILE.write_text("\n".join(lines) + "\n")
print(f"Generated {COMPOSE_FILE} for {NUM_WORKERS} workers.")

